<a href="https://colab.research.google.com/github/RogerReateguiUTEC/Tareas_Programacion101/blob/main/TAREAS/EXAMEN3_ROGER_REATEGUI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Examen 3 - ROGER REATEGUI SOTO

 # **Pregunta 1:**

a) Crea un array unidimensional que contenga los números primos entre 1 y 50.

In [18]:
import numpy as np

In [45]:
numeros = np.arange(1, 51)

def es_primo(num):
    if num < 2:
        return False
    if num%2 == 0 and num > 2:
        return False

    for i in range(3, int(np.sqrt(num)) + 1, 2):
        if num % i == 0:
            return False
    return True

primos = np.array([i for i in numeros if es_primo(i)])
primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47])

b) Convierte el array unidimensional anterior en una matriz de forma (n, 2), donde n es el número adecuado de filas. Si es necesario, agrega ceros al final del array para completar la matriz.

In [25]:
# Calcular cuántos ceros necesitamos agregar
n_elementos = primos.size

if n_elementos % 2 != 0:
    # Si el número de elementos no es par, agregar un cero
    primos = np.append(primos, 0)

# Redimensionar el array a la forma (n, 2)
matriz_reshaped = primos.reshape(-1, 2)

print(matriz_reshaped)

[[ 2  3]
 [ 5  7]
 [11 13]
 [17 19]
 [23 29]
 [31 37]
 [41 43]
 [47  0]]


 c) Calcula la suma de cada fila y crea un nuevo array que contenga estos valores.

In [27]:
suma_filas = np.sum(matriz_reshaped, axis=1)
suma_filas #cada elemento de este array es la suma de las filas de matriz_reshaped

array([ 5, 12, 24, 36, 52, 68, 84, 47])

#  **Pregunta 2:**

 a) Crea un array bidimensional de forma (4, 4) que contenga números enteros aleatorios entre 1 y 100.

In [32]:
array_bidimensional = np.random.randint(1, 101, size=(4, 4))
array_bidimensional

array([[57, 22, 33, 95],
       [19, 90, 84, 39],
       [32, 39, 72, 11],
       [ 6, 21, 32, 73]])

 b) Cambia el tipo de datos del array a float64 y divide todos los elementos or 3.7.

In [33]:
array_bidimensional = array_bidimensional.astype(np.float64)
array_bidimensional

array([[57., 22., 33., 95.],
       [19., 90., 84., 39.],
       [32., 39., 72., 11.],
       [ 6., 21., 32., 73.]])

In [35]:
array_resultado = array_bidimensional / 3.7
array_resultado

array([[15.40540541,  5.94594595,  8.91891892, 25.67567568],
       [ 5.13513514, 24.32432432, 22.7027027 , 10.54054054],
       [ 8.64864865, 10.54054054, 19.45945946,  2.97297297],
       [ 1.62162162,  5.67567568,  8.64864865, 19.72972973]])

c) Calcula y muestra las siguientes propiedades del array resultante:

* Dimensiones (ndim)
* Forma(shape)
* Tamañototal (size)
* Tipodedatos (dtype)

In [36]:
print("Dimensiones (ndim):", array_resultado.ndim)
print("Forma (shape):", array_resultado.shape)
print("Tamaño total (size):", array_resultado.size)
print("Tipo de datos (dtype):", array_resultado.dtype)

Dimensiones (ndim): 2
Forma (shape): (4, 4)
Tamaño total (size): 16
Tipo de datos (dtype): float64


# **Pregunta 3:**

 a) Crea un array x que contenga 100 valores equiespaciados entre-10 y 10.

In [37]:
x = np.linspace(-10, 10, 100)
x

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

 b) Calcula el valor de la función f(x)=e**(-x**2) para cada elemento de x.

In [40]:
expo_x = np.exp(-x**2)
expo_x

array([3.72007598e-44, 2.03026390e-42, 1.02118442e-40, 4.73376699e-39,
       2.02236984e-37, 7.96279046e-36, 2.88948872e-34, 9.66335032e-33,
       2.97841666e-31, 8.46046409e-30, 2.21489900e-28, 5.34397817e-27,
       1.18830091e-25, 2.43522554e-24, 4.59941880e-23, 8.00603952e-22,
       1.28435035e-20, 1.89889213e-19, 2.58742690e-18, 3.24927813e-17,
       3.76059612e-16, 4.01122945e-15, 3.94320471e-14, 3.57249927e-13,
       2.98295005e-12, 2.29546576e-11, 1.62797100e-10, 1.06407812e-09,
       6.40990174e-09, 3.55860870e-08, 1.82079103e-07, 8.58600196e-07,
       3.73140910e-06, 1.49453385e-05, 5.51683065e-05, 1.87682835e-04,
       5.88451217e-04, 1.70038545e-03, 4.52830117e-03, 1.11140983e-02,
       2.51399360e-02, 5.24089078e-02, 1.00692485e-01, 1.78295348e-01,
       2.90960459e-01, 4.37601640e-01, 6.06561603e-01, 7.74857597e-01,
       9.12262625e-01, 9.89848834e-01, 9.89848834e-01, 9.12262625e-01,
       7.74857597e-01, 6.06561603e-01, 4.37601640e-01, 2.90960459e-01,
      

c) Encuentra el valor máximo y mínimo de f(x) y las posiciones en el array donde ocurren.

In [41]:
max_value = np.max(expo_x)
min_value = np.min(expo_x)

max_index = np.argmax(expo_x)
min_index = np.argmin(expo_x)

# Mostrar los resultados
print("Valor máximo:", max_value)
print("Valor mínimo:", min_value)
print("Posición del valor máximo:", max_index)
print("Posición del valor mínimo:", min_index)

Valor máximo: 0.9898488339361309
Valor mínimo: 3.720075976020836e-44
Posición del valor máximo: 49
Posición del valor mínimo: 0


# **Pregunta 4: Indexación y Slicing Avanzado**

 Dado el siguiente array bidimensional:

 array = np.arange(1, 101).reshape(10, 10)



 a) Extrae un subarray que contenga los elementos en posiciones pares de filas y columnas (es decir, filas y
 columnas con índices 0, 2, 4, 6, 8).

In [42]:
array = np.arange(1, 101).reshape(10, 10)
array

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [43]:
subarray = array[::2, ::2]
subarray

array([[ 1,  3,  5,  7,  9],
       [21, 23, 25, 27, 29],
       [41, 43, 45, 47, 49],
       [61, 63, 65, 67, 69],
       [81, 83, 85, 87, 89]])

 b) Reemplaza todos los elementos que son múltiplos de 3 por-1.

In [44]:
# Reemplazar los elementos que son múltiplos de 3 por -1
array[array % 3 == 0] = -1
array

array([[  1,   2,  -1,   4,   5,  -1,   7,   8,  -1,  10],
       [ 11,  -1,  13,  14,  -1,  16,  17,  -1,  19,  20],
       [ -1,  22,  23,  -1,  25,  26,  -1,  28,  29,  -1],
       [ 31,  32,  -1,  34,  35,  -1,  37,  38,  -1,  40],
       [ 41,  -1,  43,  44,  -1,  46,  47,  -1,  49,  50],
       [ -1,  52,  53,  -1,  55,  56,  -1,  58,  59,  -1],
       [ 61,  62,  -1,  64,  65,  -1,  67,  68,  -1,  70],
       [ 71,  -1,  73,  74,  -1,  76,  77,  -1,  79,  80],
       [ -1,  82,  83,  -1,  85,  86,  -1,  88,  89,  -1],
       [ 91,  92,  -1,  94,  95,  -1,  97,  98,  -1, 100]])

c) Utiliza indexación avanzada para extraer todos los números primos del array original y crea un nuevo array con estos valores.

In [ ]:
def es_primo(num):
    if num < 2:
        return False
    if num%2 == 0 and num > 2:
        return False

    for i in range(3, int(np.sqrt(num)) + 1, 2):
        if num % i == 0:
            return False
    return True

In [47]:
mascara_primos = np.vectorize(es_primo)(array)
mascara_primos

array([[False,  True, False, False,  True, False,  True, False, False,
        False],
       [ True, False,  True, False, False, False,  True, False,  True,
        False],
       [False, False,  True, False, False, False, False, False,  True,
        False],
       [ True, False, False, False, False, False,  True, False, False,
        False],
       [ True, False,  True, False, False, False,  True, False, False,
        False],
       [False, False,  True, False, False, False, False, False,  True,
        False],
       [ True, False, False, False, False, False,  True, False, False,
        False],
       [ True, False,  True, False, False, False, False, False,  True,
        False],
       [False, False,  True, False, False, False, False, False,  True,
        False],
       [False, False, False, False, False, False,  True, False, False,
        False]])

In [48]:
primos = array[mascara_primos]
primos

array([ 2,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61,
       67, 71, 73, 79, 83, 89, 97])

 # **Pregunta 5:**

a) Crea tres arrays unidimensionales de longitud 5 con números aleatorios entre 0 y 1.

In [49]:
array1 = np.random.rand(5)
array2 = np.random.rand(5)
array3 = np.random.rand(5)

print("Array 1:", array1)
print("Array 2:", array2)
print("Array 3:", array3)

Array 1: [0.22536399 0.40837701 0.55776539 0.65694053 0.03450467]
Array 2: [0.97280992 0.33045217 0.40637504 0.77592583 0.21481269]
Array 3: [0.10217555 0.21195847 0.13227315 0.44311069 0.77912181]


b) Combina estos arrays para formar una matriz de forma (5, 3).

In [50]:
matriz = np.column_stack((array1, array2, array3))
print("Matriz combinada:", matriz)

Matriz combinada: [[0.22536399 0.97280992 0.10217555]
 [0.40837701 0.33045217 0.21195847]
 [0.55776539 0.40637504 0.13227315]
 [0.65694053 0.77592583 0.44311069]
 [0.03450467 0.21481269 0.77912181]]


c) Agrega una columna de unos al principio de la matriz resultante, obteniendo una matriz de forma (5, 4).

In [51]:
columna_unos = np.ones((matriz.shape[0], 1))
columna_unos

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [52]:
matriz_con_unos = np.column_stack((columna_unos, matriz))
matriz_con_unos

array([[1.        , 0.22536399, 0.97280992, 0.10217555],
       [1.        , 0.40837701, 0.33045217, 0.21195847],
       [1.        , 0.55776539, 0.40637504, 0.13227315],
       [1.        , 0.65694053, 0.77592583, 0.44311069],
       [1.        , 0.03450467, 0.21481269, 0.77912181]])

 d) Reordena las columnas de la matriz para que la columna de unos esté al final.


In [53]:
matriz_reordenada = matriz_con_unos[:, [1, 2, 3, 0]]
matriz_reordenada

array([[0.22536399, 0.97280992, 0.10217555, 1.        ],
       [0.40837701, 0.33045217, 0.21195847, 1.        ],
       [0.55776539, 0.40637504, 0.13227315, 1.        ],
       [0.65694053, 0.77592583, 0.44311069, 1.        ],
       [0.03450467, 0.21481269, 0.77912181, 1.        ]])

#  **Pregunta 6:**

 a) Crea una matriz simétrica positiva definida de tamaño 3x3.

In [54]:
A = np.random.rand(3, 3)
matriz_simetrica_positiva_definida = np.dot(A, A.T)
matriz_simetrica_positiva_definida

array([[1.20306789, 1.01130045, 0.90575028],
       [1.01130045, 1.2115518 , 0.87618187],
       [0.90575028, 0.87618187, 0.72891112]])

 b) Calcula sus valores y vectores propios (eigenvalores y eigenvectores).

In [55]:
eigenvalores, eigenvectores = np.linalg.eig(matriz_simetrica_positiva_definida)

print("Eigenvalores:", eigenvalores)
print("Eigenvectores:\n", eigenvectores)

Eigenvalores: [2.93748527 0.19817556 0.00786998]
Eigenvectores:
 [[-0.61589643 -0.66402623 -0.42395843]
 [-0.61245224  0.74205067 -0.27251248]
 [-0.49555407 -0.09181483  0.86371071]]
