<a href="https://colab.research.google.com/github/RogerReateguiUTEC/Tareas_Programacion101/blob/main/TAREAS/EXAMEN3_ROGER_REATEGUI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Examen 3 - ROGER REATEGUI SOTO

 # **Pregunta 1:**

a) Crea un array unidimensional que contenga los números primos entre 1 y 50.

In [18]:
import numpy as np

In [45]:
numeros = np.arange(1, 51)

def es_primo(num):
    if num < 2:
        return False
    if num%2 == 0 and num > 2:
        return False

    for i in range(3, int(np.sqrt(num)) + 1, 2):
        if num % i == 0:
            return False
    return True

primos = np.array([i for i in numeros if es_primo(i)])
primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47])

b) Convierte el array unidimensional anterior en una matriz de forma (n, 2), donde n es el número adecuado de filas. Si es necesario, agrega ceros al final del array para completar la matriz.

In [25]:
# Calcular cuántos ceros necesitamos agregar
n_elementos = primos.size

if n_elementos % 2 != 0:
    # Si el número de elementos no es par, agregar un cero
    primos = np.append(primos, 0)

# Redimensionar el array a la forma (n, 2)
matriz_reshaped = primos.reshape(-1, 2)

print(matriz_reshaped)

[[ 2  3]
 [ 5  7]
 [11 13]
 [17 19]
 [23 29]
 [31 37]
 [41 43]
 [47  0]]


 c) Calcula la suma de cada fila y crea un nuevo array que contenga estos valores.

In [27]:
suma_filas = np.sum(matriz_reshaped, axis=1)
suma_filas #cada elemento de este array es la suma de las filas de matriz_reshaped

array([ 5, 12, 24, 36, 52, 68, 84, 47])

#  **Pregunta 2:**

 a) Crea un array bidimensional de forma (4, 4) que contenga números enteros aleatorios entre 1 y 100.

In [32]:
array_bidimensional = np.random.randint(1, 101, size=(4, 4))
array_bidimensional

array([[57, 22, 33, 95],
       [19, 90, 84, 39],
       [32, 39, 72, 11],
       [ 6, 21, 32, 73]])

 b) Cambia el tipo de datos del array a float64 y divide todos los elementos or 3.7.

In [33]:
array_bidimensional = array_bidimensional.astype(np.float64)
array_bidimensional

array([[57., 22., 33., 95.],
       [19., 90., 84., 39.],
       [32., 39., 72., 11.],
       [ 6., 21., 32., 73.]])

In [35]:
array_resultado = array_bidimensional / 3.7
array_resultado

array([[15.40540541,  5.94594595,  8.91891892, 25.67567568],
       [ 5.13513514, 24.32432432, 22.7027027 , 10.54054054],
       [ 8.64864865, 10.54054054, 19.45945946,  2.97297297],
       [ 1.62162162,  5.67567568,  8.64864865, 19.72972973]])

c) Calcula y muestra las siguientes propiedades del array resultante:

* Dimensiones (ndim)
* Forma(shape)
* Tamañototal (size)
* Tipodedatos (dtype)

In [36]:
print("Dimensiones (ndim):", array_resultado.ndim)
print("Forma (shape):", array_resultado.shape)
print("Tamaño total (size):", array_resultado.size)
print("Tipo de datos (dtype):", array_resultado.dtype)

Dimensiones (ndim): 2
Forma (shape): (4, 4)
Tamaño total (size): 16
Tipo de datos (dtype): float64


# **Pregunta 3:**

 a) Crea un array x que contenga 100 valores equiespaciados entre-10 y 10.

In [37]:
x = np.linspace(-10, 10, 100)
x

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

 b) Calcula el valor de la función f(x)=e**(-x**2) para cada elemento de x.

In [40]:
expo_x = np.exp(-x**2)
expo_x

array([3.72007598e-44, 2.03026390e-42, 1.02118442e-40, 4.73376699e-39,
       2.02236984e-37, 7.96279046e-36, 2.88948872e-34, 9.66335032e-33,
       2.97841666e-31, 8.46046409e-30, 2.21489900e-28, 5.34397817e-27,
       1.18830091e-25, 2.43522554e-24, 4.59941880e-23, 8.00603952e-22,
       1.28435035e-20, 1.89889213e-19, 2.58742690e-18, 3.24927813e-17,
       3.76059612e-16, 4.01122945e-15, 3.94320471e-14, 3.57249927e-13,
       2.98295005e-12, 2.29546576e-11, 1.62797100e-10, 1.06407812e-09,
       6.40990174e-09, 3.55860870e-08, 1.82079103e-07, 8.58600196e-07,
       3.73140910e-06, 1.49453385e-05, 5.51683065e-05, 1.87682835e-04,
       5.88451217e-04, 1.70038545e-03, 4.52830117e-03, 1.11140983e-02,
       2.51399360e-02, 5.24089078e-02, 1.00692485e-01, 1.78295348e-01,
       2.90960459e-01, 4.37601640e-01, 6.06561603e-01, 7.74857597e-01,
       9.12262625e-01, 9.89848834e-01, 9.89848834e-01, 9.12262625e-01,
       7.74857597e-01, 6.06561603e-01, 4.37601640e-01, 2.90960459e-01,
      

c) Encuentra el valor máximo y mínimo de f(x) y las posiciones en el array donde ocurren.

In [41]:
max_value = np.max(expo_x)
min_value = np.min(expo_x)

max_index = np.argmax(expo_x)
min_index = np.argmin(expo_x)

# Mostrar los resultados
print("Valor máximo:", max_value)
print("Valor mínimo:", min_value)
print("Posición del valor máximo:", max_index)
print("Posición del valor mínimo:", min_index)

Valor máximo: 0.9898488339361309
Valor mínimo: 3.720075976020836e-44
Posición del valor máximo: 49
Posición del valor mínimo: 0


# **Pregunta 4: Indexación y Slicing Avanzado**

 Dado el siguiente array bidimensional:

 array = np.arange(1, 101).reshape(10, 10)



 a) Extrae un subarray que contenga los elementos en posiciones pares de filas y columnas (es decir, filas y
 columnas con índices 0, 2, 4, 6, 8).

In [42]:
array = np.arange(1, 101).reshape(10, 10)
array

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [43]:
subarray = array[::2, ::2]
subarray

array([[ 1,  3,  5,  7,  9],
       [21, 23, 25, 27, 29],
       [41, 43, 45, 47, 49],
       [61, 63, 65, 67, 69],
       [81, 83, 85, 87, 89]])

 b) Reemplaza todos los elementos que son múltiplos de 3 por-1.

In [44]:
# Reemplazar los elementos que son múltiplos de 3 por -1
array[array % 3 == 0] = -1
array

array([[  1,   2,  -1,   4,   5,  -1,   7,   8,  -1,  10],
       [ 11,  -1,  13,  14,  -1,  16,  17,  -1,  19,  20],
       [ -1,  22,  23,  -1,  25,  26,  -1,  28,  29,  -1],
       [ 31,  32,  -1,  34,  35,  -1,  37,  38,  -1,  40],
       [ 41,  -1,  43,  44,  -1,  46,  47,  -1,  49,  50],
       [ -1,  52,  53,  -1,  55,  56,  -1,  58,  59,  -1],
       [ 61,  62,  -1,  64,  65,  -1,  67,  68,  -1,  70],
       [ 71,  -1,  73,  74,  -1,  76,  77,  -1,  79,  80],
       [ -1,  82,  83,  -1,  85,  86,  -1,  88,  89,  -1],
       [ 91,  92,  -1,  94,  95,  -1,  97,  98,  -1, 100]])

c) Utiliza indexación avanzada para extraer todos los números primos del array original y crea un nuevo array con estos valores.

In [ ]:
def es_primo(num):
    if num < 2:
        return False
    if num%2 == 0 and num > 2:
        return False

    for i in range(3, int(np.sqrt(num)) + 1, 2):
        if num % i == 0:
            return False
    return True

In [47]:
mascara_primos = np.vectorize(es_primo)(array)
mascara_primos

array([[False,  True, False, False,  True, False,  True, False, False,
        False],
       [ True, False,  True, False, False, False,  True, False,  True,
        False],
       [False, False,  True, False, False, False, False, False,  True,
        False],
       [ True, False, False, False, False, False,  True, False, False,
        False],
       [ True, False,  True, False, False, False,  True, False, False,
        False],
       [False, False,  True, False, False, False, False, False,  True,
        False],
       [ True, False, False, False, False, False,  True, False, False,
        False],
       [ True, False,  True, False, False, False, False, False,  True,
        False],
       [False, False,  True, False, False, False, False, False,  True,
        False],
       [False, False, False, False, False, False,  True, False, False,
        False]])

In [48]:
primos = array[mascara_primos]
primos

array([ 2,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61,
       67, 71, 73, 79, 83, 89, 97])

 # **Pregunta 5:**

a) Crea tres arrays unidimensionales de longitud 5 con números aleatorios entre 0 y 1.

In [49]:
array1 = np.random.rand(5)
array2 = np.random.rand(5)
array3 = np.random.rand(5)

print("Array 1:", array1)
print("Array 2:", array2)
print("Array 3:", array3)

Array 1: [0.22536399 0.40837701 0.55776539 0.65694053 0.03450467]
Array 2: [0.97280992 0.33045217 0.40637504 0.77592583 0.21481269]
Array 3: [0.10217555 0.21195847 0.13227315 0.44311069 0.77912181]


b) Combina estos arrays para formar una matriz de forma (5, 3).

In [50]:
matriz = np.column_stack((array1, array2, array3))
print("Matriz combinada:", matriz)

Matriz combinada: [[0.22536399 0.97280992 0.10217555]
 [0.40837701 0.33045217 0.21195847]
 [0.55776539 0.40637504 0.13227315]
 [0.65694053 0.77592583 0.44311069]
 [0.03450467 0.21481269 0.77912181]]


c) Agrega una columna de unos al principio de la matriz resultante, obteniendo una matriz de forma (5, 4).

In [51]:
columna_unos = np.ones((matriz.shape[0], 1))
columna_unos

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [52]:
matriz_con_unos = np.column_stack((columna_unos, matriz))
matriz_con_unos

array([[1.        , 0.22536399, 0.97280992, 0.10217555],
       [1.        , 0.40837701, 0.33045217, 0.21195847],
       [1.        , 0.55776539, 0.40637504, 0.13227315],
       [1.        , 0.65694053, 0.77592583, 0.44311069],
       [1.        , 0.03450467, 0.21481269, 0.77912181]])

 d) Reordena las columnas de la matriz para que la columna de unos esté al final.


In [53]:
matriz_reordenada = matriz_con_unos[:, [1, 2, 3, 0]]
matriz_reordenada

array([[0.22536399, 0.97280992, 0.10217555, 1.        ],
       [0.40837701, 0.33045217, 0.21195847, 1.        ],
       [0.55776539, 0.40637504, 0.13227315, 1.        ],
       [0.65694053, 0.77592583, 0.44311069, 1.        ],
       [0.03450467, 0.21481269, 0.77912181, 1.        ]])

#  **Pregunta 6:**

 a) Crea una matriz simétrica positiva definida de tamaño 3x3.

In [54]:
A = np.random.rand(3, 3)
matriz_simetrica_positiva_definida = np.dot(A, A.T)
matriz_simetrica_positiva_definida

array([[1.20306789, 1.01130045, 0.90575028],
       [1.01130045, 1.2115518 , 0.87618187],
       [0.90575028, 0.87618187, 0.72891112]])

 b) Calcula sus valores y vectores propios (eigenvalores y eigenvectores).

In [55]:
eigenvalores, eigenvectores = np.linalg.eig(matriz_simetrica_positiva_definida)

print("Eigenvalores:", eigenvalores)
print("Eigenvectores:\n", eigenvectores)

Eigenvalores: [2.93748527 0.19817556 0.00786998]
Eigenvectores:
 [[-0.61589643 -0.66402623 -0.42395843]
 [-0.61245224  0.74205067 -0.27251248]
 [-0.49555407 -0.09181483  0.86371071]]


c) Verifica que la multiplicación de la matriz original por un vector propio es igual al producto del eigenvalor correspondiente por el vector propio.



In [57]:
eigenvalor0 = eigenvalores[0]
v = eigenvectores[:, 0]

# Verificar que A * v es igual a eigenvalor0 * v
resultado_multiplicacion = np.dot(matriz_simetrica_positiva_definida, v)
producto_eigenvalor = eigenvalor0 * v

print("Resultado de A * v:\n", resultado_multiplicacion)
print("Producto de eigenvalor0 * v:\n", producto_eigenvalor)

Resultado de A * v:
 [-1.80918669 -1.79906945 -1.45568279]
Producto de eigenvalor0 * v:
 [-1.80918669 -1.79906945 -1.45568279]


#  **Pregunta 7:**

a) Construye un sistema de ecuaciones lineales con tres ecuaciones y tres incógnitas donde la matriz de coeficientes es singular (no invertible).

In [58]:
A = np.array([[1, 2, 3],
              [2, 4, 6],
              [3, 5, 7]])

b = np.array([6, 12, 18]) #vector de resultados

In [60]:
# Calcular el determinante de A para verificar que es singular (determinante debe ser cero)
determinante = np.linalg.det(A)
determinante

0.0

b) Intenta resolver el sistema utilizando np.linalg.solve() y explica el resultado obtenido.

In [63]:
try:
  solucion = np.linalg.solve(A, b)
except:
  print("El sistema no tiene solucion una solución única por ser una matriz singular")

El sistema no tiene solucion una solución única por ser una matriz singular


#  **Pregunta 8:**

a) Crea un array de forma (4, 4, 4) con números enteros aleatorios entre 0 y 100.

In [64]:
array = np.random.randint(0, 101, size=(4, 4, 4))
array

array([[[  1,   4,  44,  92],
        [ 57,  55,  11,  38],
        [ 84,  93,  97,  90],
        [ 93,  76,  55,  40]],

       [[ 30,  19,  87,  50],
        [ 15,  43,  37,  40],
        [ 54,  62,  91,  34],
        [ 97,  94,  79,  61]],

       [[ 62,  89,  14,  68],
        [ 36,  62,  44,  12],
        [ 39,  95,   0,  56],
        [ 44,  56,  67,  95]],

       [[ 70,  65,   9,  70],
        [ 51,   8,  74, 100],
        [ 94,  50,  28,  71],
        [ 83,  31,  18,  26]]])

b) Calcula la suma a lo largo del eje 0, obteniendo un array de forma (4, 4).

In [65]:
suma_eje_0 = np.sum(array, axis=0)
suma_eje_0

array([[163, 177, 154, 280],
       [159, 168, 166, 190],
       [271, 300, 216, 251],
       [317, 257, 219, 222]])

 c) Calcula el promedio a lo largo del eje 1, obteniendo un array de forma (4, 4).

In [66]:
promedio_eje_1 = np.mean(array, axis=1)
promedio_eje_1

array([[58.75, 57.  , 51.75, 65.  ],
       [49.  , 54.5 , 73.5 , 46.25],
       [45.25, 75.5 , 31.25, 57.75],
       [74.5 , 38.5 , 32.25, 66.75]])

 d) Reestructura el array original en una nueva forma de (8, 8) sin perder datos.

In [68]:
nuevo_array = array.reshape(8, 8)
nuevo_array

array([[  1,   4,  44,  92,  57,  55,  11,  38],
       [ 84,  93,  97,  90,  93,  76,  55,  40],
       [ 30,  19,  87,  50,  15,  43,  37,  40],
       [ 54,  62,  91,  34,  97,  94,  79,  61],
       [ 62,  89,  14,  68,  36,  62,  44,  12],
       [ 39,  95,   0,  56,  44,  56,  67,  95],
       [ 70,  65,   9,  70,  51,   8,  74, 100],
       [ 94,  50,  28,  71,  83,  31,  18,  26]])

 # **Pregunta 9:**

 Se define una secuencia de números donde cada elemento es el factorial del índice correspondiente.
 Formalmente:
 an = n! para n=1,2,...10

a) Usando NumPy, crea un array que contenga los primeros 10 elementos de esta secuencia sin utilizar bucles
 explícitos.

In [70]:
indices = np.arange(1, 11)
factoriales = np.vectorize(np.math.factorial)(indices)
factoriales

<ipython-input-70-a5eda17736ec>:2: DeprecationWarning: `np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`
  factoriales = np.vectorize(np.math.factorial)(indices)


array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

 b) Calcula la suma de todos los elementos del array creado.


In [71]:
suma_total = np.sum(factoriales)
suma_total

4037913

 c) Dado que los factoriales pueden ser números muy grandes, cambia el tipo de datos del array a object para
 manejar enteros arbitrariamente grandes y recalcula la suma.

In [72]:
factoriales_object = factoriales.astype(object)
suma_total_object = np.sum(factoriales_object)
suma_total_object

4037913

#  **Pregunta 10:**


 a) Simula un conjunto de datos que represente las alturas (en cm) de 500 personas, siguiendo una distribución
 normal con media 170 y desviación estándar 10.

In [73]:
media = 170
desviacion_estandar = 10
num_personas = 500

alturas = np.random.normal(loc=media, scale=desviacion_estandar, size=num_personas)
alturas

array([187.15687846, 175.60486627, 158.29600121, 181.94496148,
       175.03570284, 166.56008962, 172.59732401, 170.49912803,
       175.08383126, 172.91260522, 170.86485593, 156.58146426,
       149.95410369, 171.25455208, 165.20424948, 177.42354922,
       174.13987088, 180.1953497 , 174.29058423, 169.12680757,
       185.25421933, 177.15414587, 161.59230211, 166.61243091,
       194.92858203, 185.12789741, 182.30600627, 146.88637471,
       178.83224073, 162.11439542, 194.86209129, 142.99271847,
       185.11303864, 161.26993281, 162.7806434 , 184.44529172,
       168.40130148, 170.54359661, 188.19864667, 154.09697356,
       168.31778977, 182.22250619, 157.22712551, 178.2104702 ,
       163.16259756, 183.10550959, 148.61085619, 173.72572961,
       178.01604373, 154.222904  , 174.44592745, 156.40502121,
       163.42117603, 169.72967526, 169.83523222, 168.0303808 ,
       186.67607493, 164.24060496, 177.18037383, 164.56394992,
       181.28130583, 172.62340514, 161.80184627, 184.78

 c) Encuentra cuántas personas miden más de 180 cm y menos de 160 cm.

In [74]:
mas_de_180 = np.sum(alturas > 180)
menos_de_160 = np.sum(alturas < 160)

print(f"Cantidad de personas que miden más de 180 cm: {mas_de_180}")
print(f"Cantidad de personas que miden menos de 160 cm: {menos_de_160}")

Cantidad de personas que miden más de 180 cm: 81
Cantidad de personas que miden menos de 160 cm: 67


 d) Normaliza los datos de altura para que tengan media 0 y desviación estándar 1.

In [75]:
alturas_normalizadas = (alturas - np.mean(alturas)) / np.std(alturas)
alturas_normalizadas

array([ 1.75452085e+00,  5.33006764e-01, -1.29723910e+00,  1.20341080e+00,
        4.72823209e-01, -4.23391304e-01,  2.14988119e-01, -6.87590811e-03,
        4.77912327e-01,  2.48326073e-01,  3.17962965e-02, -1.47853488e+00,
       -2.17931447e+00,  7.30029131e-02, -5.66758347e-01,  7.25314979e-01,
        3.78097603e-01,  1.01840620e+00,  3.94034089e-01, -1.51985587e-01,
        1.55333297e+00,  6.96828167e-01, -9.48687013e-01, -4.17856716e-01,
        2.57630370e+00,  1.53997564e+00,  1.24158781e+00, -2.50369728e+00,
        8.74270546e-01, -8.93480671e-01,  2.56927294e+00, -2.91541395e+00,
        1.53840447e+00, -9.82774464e-01, -8.23031361e-01,  1.46779666e+00,
       -2.28700873e-01, -2.17378366e-03,  1.86467781e+00, -1.74124586e+00,
       -2.37531432e-01,  1.23275848e+00, -1.41026242e+00,  8.08524298e-01,
       -7.82643385e-01,  1.32612759e+00, -2.32134996e+00,  3.34306150e-01,
        7.87965570e-01, -1.72792993e+00,  4.10460139e-01, -1.49719204e+00,
       -7.55301201e-01, -