<a href="https://colab.research.google.com/github/RogerReateguiUTEC/Tareas_Programacion101/blob/main/TAREAS/EXAMEN3_ROGER_REATEGUI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Examen 3 - ROGER REATEGUI SOTO

 ## Pregunta 1:

a) Crea un array unidimensional que contenga los números primos entre 1 y 50.

In [18]:
import numpy as np

In [22]:
numeros = np.arange(1, 51)

def es_primo_vectorizado(num):
    if num < 2:
        return False
    if num%2 == 0 and num > 2:
        return False

    for i in range(3, int(np.sqrt(num)) + 1, 2):
        if num % i == 0:
            return False
    return True

primos = np.array([i for i in numeros if es_primo_vectorizado(i)])
primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47])

b) Convierte el array unidimensional anterior en una matriz de forma (n, 2), donde n es el número adecuado de filas. Si es necesario, agrega ceros al final del array para completar la matriz.

In [25]:
# Calcular cuántos ceros necesitamos agregar
n_elementos = primos.size

if n_elementos % 2 != 0:
    # Si el número de elementos no es par, agregar un cero
    primos = np.append(primos, 0)

# Redimensionar el array a la forma (n, 2)
matriz_reshaped = primos.reshape(-1, 2)

print(matriz_reshaped)

[[ 2  3]
 [ 5  7]
 [11 13]
 [17 19]
 [23 29]
 [31 37]
 [41 43]
 [47  0]]


 c) Calcula la suma de cada fila y crea un nuevo array que contenga estos valores.

In [27]:
suma_filas = np.sum(matriz_reshaped, axis=1)
suma_filas #cada elemento de este array es la suma de las filas de matriz_reshaped

array([ 5, 12, 24, 36, 52, 68, 84, 47])

#  Pregunta 2:

 a) Crea un array bidimensional de forma (4, 4) que contenga números enteros aleatorios entre 1 y 100.

In [29]:
array_bidimensional = np.random.randint(1, 101)
array_bidimensional

19

In [2]:
zeros_array = np.zeros((3, 3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arange_array = np.arange(10)
arange_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
random_array = np.random.rand(2, 3)
random_array

array([[0.2252731 , 0.40899931, 0.1609544 ],
       [0.76470806, 0.79590158, 0.56576312]])

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Suma:", a + b)
print("Resta:", a - b)
print("Multiplicación:", a * b)
print("División:", a / b)

Suma: [5 7 9]
Resta: [-3 -3 -3]
Multiplicación: [ 4 10 18]
División: [0.25 0.4  0.5 ]


In [8]:
array = np.array([1, 5, 2, 8, 3])

print("Suma total:", array.sum())
print("Promedio:", array.mean())
print("Mediana:", np.median(array))
print("Desviación estándar:", array.std())

Suma total: 19
Promedio: 3.8
Mediana: 3.0
Desviación estándar: 2.4819347291981715


In [9]:
angles = np.array([0, np.pi/2, np.pi])

print("Seno:", np.sin(angles))
print("Coseno:", np.cos(angles))
print("Exponencial:", np.exp(array))

Seno: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Coseno: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Exponencial: [2.71828183e+00 1.48413159e+02 7.38905610e+00 2.98095799e+03
 2.00855369e+01]


In [10]:
array = np.array([[10, 20, 30], [40, 50, 60]])

# Acceder al elemento en la fila 1, columna 2
element = array[1, 2]
print("Elemento en (1, 2):", element)

Elemento en (1, 2): 60


In [11]:
# Obtener la primera fila
first_row = array[0, :]
print("Primera fila:", first_row)

# Obtener la segunda columna
second_col = array[:, 1]
print("Segunda columna:", second_col)

# Obtener un subarray de forma (2, 2)
subarray = array[:, :2]
print("Subarray:\n", subarray)

Primera fila: [10 20 30]
Segunda columna: [20 50]
Subarray:
 [[10 20]
 [40 50]]


In [12]:
second_col

array([20, 50])

In [13]:
array = np.arange(12)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
reshaped_array = array.reshape(3, 4)
print("Array reestructurado:\n", reshaped_array)

Array reestructurado:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
reshaped_array = array.reshape(2, -1)
print("Array reestructurado con -1:\n", reshaped_array)


Array reestructurado con -1:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [16]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[2, 0], [1, 2]])

product = np.matmul(matrix1, matrix2)
product

array([[ 4,  4],
       [10,  8]])

In [17]:
matrix1 * matrix2

array([[2, 0],
       [3, 8]])